routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'AdminController@index')->name('home');
//Route::get('{id}/profile', 'Resource\DisputeUserResource@edit')->name('dispute-users.edit');
Route::get('{id}/profile', 'Resource\DisputeUserResource@edit')->name('dispute-user.edit');

Route::resource('users', 'Resource\UserResource');
Route::resource('transporters', 'Resource\TransporterResource');
Route::resource('disputeuser', 'Resource\DisputeUserResource');

	

Route::resource('categories', 'Resource\CategoryResource');
Route::get('subcategory', 'Resource\CategoryResource@subcategory');
Route::resource('categories.products', 'Resource\ProductResource');
Route::resource('products', 'Resource\ProductResource');
Route::delete('productimage/{id}', 'Resource\ProductResource@imagedestroy')->name('productimage.destroy');
Route::resource('orders', 'Resource\OrderResource');
Route::resource('shops', 'Resource\ShopResource');
Route::resource('zones', 'Resource\ZoneResource');
Route::resource('cuisines', 'Resource\CuisineResource');
Route::resource('demoapp', 'ManageappController');
Route::resource('promocodes', 'Resource\PromocodeResource');
Route::resource('emailtemplate', 'Resource\EmailTemplateResource');
Route::resource('translation', 'Resource\TranslationResource');
Route::get('disputes/{name}', 'Resource\DisputeResource@index');
Route::resource('dispute', 'Resource\DisputeResource');
Route::resource('banner', 'Resource\ShopBannerResource');
Route::resource('notice', 'Resource\NoticeBoardResource');
Route::resource('disputehelp', 'Resource\DisputeHelpResource');
Route::get('/settings', 'AdminController@settings')->name('settings');;
Route::post('/settings', 'AdminController@settings_store')->name('settings.store');;
//Route::get('/accsetting', 'AdminController@account_setting')->name('accsetting');;
Route::post('/setting/add', 'AdminController@AccountSettingStore')->name('accsetting.store');;

Route::get('/send/push', 'AdminController@push')->name('push');
Route::post('/send/push', 'AdminController@send_push')->name('send.push');

Route::get('/chat','Resource\DisputeResource@chatWithUser');

Route::post('/pages', 'AdminController@pages')->name('pages.update');

//pages

Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::get('/faq', 'AdminController@faq')->name('faq');
Route::get('/about', 'AdminController@about')->name('about');
Route::get('/help', 'AdminController@help')->name('help');
Route::get('/refund', 'AdminController@refund')->name('refund');
Route::get('/queries', 'AdminController@queries')->name('queries');
Route::get('/otherterms', 'AdminController@otherterms')->name('otherterms');
Route::get('/contact', 'AdminController@contact')->name('contact');

Route::get('/leadres', 'AdminController@restuarant_leads')->name('leadres');
Route::get('/newsletter', 'AdminController@newsletter_leads')->name('newsletter');
Route::get('/enquiry_delivery', 'AdminController@enquiry_delivery')->name('enquiry_delivery');


Route::resource('addons', 'Resource\AddonsResource');
Route::get('transporters-shift', 'Resource\TransporterResource@shiftdetails');

//bulk product

Route::get('product/bulk', 'Resource\ProductResource@product_bulk')->name('product.bulk');
Route::post('product/store_bulk', 'Resource\ProductResource@product_csv')->name('product.store_bulk');

routes/user.php
<?php

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'UserController@index')->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
//abort(404, 'The resource you are looking for could not be found');
Route::get('/', 'WelcomeController@home');

// Route::get('initsetup', function () {
//     return Setting::all();
// });

Route::view('/privacy', 'static', ['page' => 'privacy' , 'title' => 'Privacy Policy' ]);

Route::view('/aboutus', 'static', ['page' => 'about' , 'title' => 'About Us' ]);

Route::view('/terms', 'static', ['page' => 'terms' , 'title' => 'Terms And Condition' ]);

Route::view('/contact', 'static', ['page' => 'contact' , 'title' => 'Contact Us' ]);

Route::view('/help', 'static', ['page' => 'help' , 'title' => 'Help' ]);

Route::view('/refund', 'static', ['page' => 'refund' , 'title' => 'Refund' ]);

Route::view('otherterms', 'static', ['page' => 'otherterms' , 'title' => 'Other Terms' ]);


Route::get('/search','WelcomeController@search');
Route::get('/enquiry-delivery','UserController@delivery');
Route::post('/enquiry-delivery','UserController@delivery_store');


Route::get('auth/facebook', 'SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'SocialLoginController@handleGoogleCallback');

Route::post('/social/login','SocialLoginController@loginWithSocial');



Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminAuth\LoginController@showLoginForm');
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'shop'], function () {
    Route::get('/', 'ShopAuth\LoginController@showLoginForm');
    Route::get('/login', 'ShopAuth\LoginController@showLoginForm');
    Route::post('/login', 'ShopAuth\LoginController@login');
    Route::post('/logout', 'ShopAuth\LoginController@logout');

    Route::get('/register', 'ShopAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'ShopAuth\RegisterController@register');

    Route::post('/password/email', 'ShopAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ShopAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'ShopAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ShopAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'transporter'], function () {
    Route::get('/login', 'TransporterAuth\LoginController@showLoginForm');
    Route::post('/login', 'TransporterAuth\LoginController@login');
    Route::post('/userlogin', 'TransporterAuth\LoginController@UserLogin');
    Route::get('/otplogin', 'TransporterAuth\LoginController@OtpLogin');
    Route::post('/logout', 'TransporterAuth\LoginController@logout');

    Route::post('/otp', 'TransporterAuth\RegisterController@OTP');
    Route::post('/verifyotp', 'TransporterAuth\RegisterController@CheckOtp');

    Route::get('/register', 'TransporterAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'TransporterAuth\RegisterController@register');

    Route::post('/password/email', 'TransporterAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'TransporterAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'TransporterAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'TransporterAuth\ResetPasswordController@showResetForm');

    Route::get('/home', 'TransporterController@index');
});

    Auth::routes();
    Route::get('login',function(){
        return redirect('/');
    });
    Route::get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('register','Auth\RegisterController@showRegistrationForm');
    Route::get('/home', 'UserController@showhome');
    Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');
    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/user/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::post('shopreg', 'ShopController@register')->name('shopregister');
    Route::post('newsletter', 'WelcomeController@newsletter')->name('newsletter');

    Route::post('/otp', 'Auth\RegisterController@OTP');
    Route::get('/dashboard', 'UserResource\OrderResource@orderprogress');
    Route::get('/profile', 'UserResource\ProfileController@index');
    Route::post('/profile', 'UserResource\ProfileController@update');
    Route::get('/changepassword', 'UserResource\ProfileController@changepassword');
    Route::post('/setpassword', 'UserResource\ProfileController@password');
    Route::resource('orders', 'UserResource\OrderResource');
    Route::resource('useraddress', 'UserResource\AddressResource');
    Route::get('/restaurants', 'UserResource\SearchResource@index');
    Route::get('/restaurant/details', 'UserResource\SearchResource@show');
    Route::get('/restaurant/viewdetails', 'UserResource\SearchResource@viewdetails');
    Route::post('mycart', 'UserResource\CartResource@addToCart');
    Route::post('addcart', 'UserResource\CartResource@store');
    Route::get('/clear/cart','UserResource\CartResource@clearCart');
    Route::get('/track/order/{id}','UserResource\SearchResource@ordertrack');
    Route::get('/product/details/{productid}/{cartId}/{shopname}/{productname}','UserResource\SearchResource@productDetails');
    // card
    Route::resource('card', 'Resource\CardResource');
    Route::get('payment', 'UserController@payment');
    Route::post('payment/confirm', 'PaymentController@payment');
    Route::any('cart/payment', 'UserController@order_payment');
    Route::get('wallet', 'UserController@wallet');
    Route::post('wallet', 'PaymentController@add_money');
    Route::post('/rating', 'UserResource\OrderResource@rate_review');
    Route::get('user/chat', 'UserResource\OrderResource@chatWithUser');
    Route::get('addons/{id}', 'Resource\ProductResource@show');
    Route::get('checkRipplePayment','PaymentController@checkRipplePayment');
    Route::get('checkEtherPayment','PaymentController@checkEtherPayment');
    // swiggy design
    Route::get('payments', 'UserController@payment');
    Route::resource('favourite', 'Resource\FavoriteResource');
    Route::get('offers', 'UserResource\SearchResource@offers');
    Route::get('legal', 'UserResource\SearchResource@legal');
    Route::get('faq', 'UserResource\SearchResource@faq');
    Route::get('queries', 'UserResource\SearchResource@queries');
    Route::post('wallet/promocode', 'UserResource\WalletResource@store');
    Route::post('/reorder', 'UserResource\OrderResource@reorder');
    
    //Route::get('/token','BraintreeTokenController@token');
    //Route::get('/payment','BraintreeTokenController@payment');
   // Route::post('/payment','BraintreeTokenController@do_payment');
    // Route::get('faq','WelcomeController@faq');
    // Route::get('aboutus','WelcomeController@aboutus');
    // Route::get('termcondition','WelcomeController@termcondition');

    //updatecartResource
    Route::resource('updatecart', 'UserResource\UpdateCartResource');
    Route::resource('referral', 'UserResource\ReferralResource');

    Route::get('/restaurant/details/addcart/{name}', 'UserResource\SearchResource@cart_checkout');
    Route::get('/product/search','UserResource\SearchResource@product_search');

    Route::get('/related/product','UserResource\SearchResource@product_related');

    Route::get('/product/filter','UserResource\SearchResource@product_filter');

    Route::get('/product/imageDimension','UserResource\SearchResource@product_image_dimension');

   

app/Transporter.php
<?php

namespace App;

use App\Notifications\TransporterResetPassword;
use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transporter extends Authenticatable
{
    use SoftDeletes, HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'name', 'email', 'phone', 'password', 'avatar', 'latitude', 'longitude','device_id','device_type','device_token','status','address','rating'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'created_at', 'updated_at', 'deleted_at'
    ];

    public function findForPassport($username) {
        return $this->where('phone', $username)->first();
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new TransporterResetPassword($token));
    }

    /**
     * Orders
     */
    public function orders()
    {
        $instance = $this->hasMany('App\Order');
        $instance->getQuery()->whereNotIn('status', ['CANCELLED','COMPLETED']);
        return $instance;
    }

    public function order()
    {
        $instance = $this->hasMany('App\Order');
        return $instance;
    }

    /**
     * vehicles
     */
    public function vehicles()
    {
        return $this->hasMany('App\TransporterVehicle');
    }

     /**
     * Orders
     */
    public function disputes()
    {
        return $this->hasMany('App\OrderDispute','transporter_id','id')->withTrashed();
    }

     /**
     * shift
     */
    public function shift()
    {
        return  $this->hasOne('App\TransporterShift')->get();
      
    }
}

app/Http/Controllers/TransporterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TransporterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('transporter.home');
    }
}

resources/views/admin/transporters/index.blade.php
@extends('admin.layouts.app')

@section('content')
<!-- File export table -->
<div class="row file">
    <div class="col-xs-12">
        <div class="card">
            <div class="card-header">
            @if(Setting::get('DEMO_MODE')==0)
            <div class="col-md-12" style="height:50px;color:red;">
                 ** Demo Mode : No Permission to Edit and Delete.
            </div>
            @endif
                <h4 class="card-title">@lang('transporter.index.title')</h4>
                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                        <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                        <li><a href="{{ route('admin.transporters.create') }}" class="btn btn-primary add-btn btn-darken-3">@lang('transporter.index.add_transporter')</a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard table-responsive">
                    <table class="table table-striped table-bordered file-export">
                        <thead>
                            <tr>
                                <th>@lang('transporter.index.sl_no')</th>
                                <th>@lang('transporter.index.name')</th>
                                <th>@lang('transporter.index.email')</th>
                                <th>@lang('transporter.index.address')</th>
                                <th>@lang('transporter.index.contact_details')</th>
                                <th>@lang('transporter.index.image')</th>
                                <th>@lang('transporter.index.rating')</th>
                                <th>@lang('transporter.index.action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($Users as $key=>$User)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    <td>{{$User->name}}</td>
                                    <td>
                                     @if(Setting::get('DEMO_MODE')==0)
                                    {{substr($User->email, 0, 1).'****'.substr($User->email, strpos($User->email, "@"))}}
                                    @else
                                        {{$User->email}}
                                    @endif
                                    </td>
                                    <td>{{$User->address}}</td>
                                    <td>
                                     @if(Setting::get('DEMO_MODE')==0)
                                    {{substr($User->phone, 0, 5).'****'}}
                                    @else
                                    {{$User->phone}}
                                    @endif
                                    </td>
                                    <td>
                                        @if($User->avatar) 
                                            <div class="bg-img com-img" style="background-image: url({{ asset($User->avatar) }});"></div>
                                        @else
                                            No Image
                                        @endif
                                    </td>
                                    <td class="star">
                                        <?php for($i=1;$i<=$User->rating;$i++){
                                                echo '<i class="fa fa-star" aria-hidden="true"></i>';
                                                }
                                            for($i=1;$i<=(5-$User->rating);$i++){
                                                echo '<i class="fa fa-star-o" aria-hidden="true"></i>';
                                                }
                                        ?>
                                    </td>
                                    <td>

                                        @if($User->status =='unsettled')
                                         <button   class="table-btn btn btn-icon btn-danger" form="resource-settle-{{ $User->id }}" >Unsettle</button>
                                        
                                        <form id="resource-settle-{{ $User->id }}" action="{{ route('admin.transporters.update', $User->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('PATCH') }}
                                            <input type="hidden" name="settle" value="1" />
                                        </form>
                                        @endif

                                         @if(Setting::get('DEMO_MODE')==1)
                                        <a href="{{ route('admin.transporters.edit', $User->id) }}" class="table-btn btn btn-icon btn-success"><i class="fa fa-pencil-square-o"></i></a>
                                       
                                        <button   class="table-btn btn btn-icon btn-danger" form="resource-delete-{{ $User->id }}" onclick="return confirm('Are you sure you want to delete this delivery boy?');" ><i class="fa fa-trash-o"></i></button>
                                        
                                        <form id="resource-delete-{{ $User->id }}" action="{{ route('admin.transporters.destroy', $User->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr><td cols="50">@lang('shop.index.no_record_found')</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/transporters/show.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-6">
        <h4 class="page-title">User Details</h4>
        <br>
    </div>
</div>
<div class="user-profile row m-0">
    <div class="user-prof-left-col col-md-4 col-sm-12 col-xs-12">
        <div class="card-box text-center">
            <img src="/avatar.png" class="rounded-circle mr-1" width="200">
            <h4 class="user-prof-tit">{{ $User->first_name }} {{ $User->last_name }}</h4>
            <p class="user-prof-txt"><i class="fa fa-envelope-o"></i> {{ $User->email }}</p>
            <p class="user-prof-txt"><i class="fa fa-phone"></i> {{ $User->phone }}</p>
            <div class="iframe-rwd">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d386950.6511603643!2d-73.70231446529533!3d40.738882125234106!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNueva+York!5e0!3m2!1ses-419!2sus!4v1445032011908" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
    <div class="user-prof-right-col col-md-8 col-sm-12 col-xs-12">
        <div class="user-prof-right">
            <div class="address-block">
                <div class="card-box table-responsive">
                    <h4 class="m-t-0 header-title"><b>Address List</b></h4>
                    <hr>
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Address</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($User->addresses as $Index => $Address)
                            <tr>
                                <td>{{ $Index + 1 }}</td>
                                <td>{{ $Address->map_address }}</td>
                                <td>
                                    <a href="#" class="btn btn-icon waves-effect btn-default waves-light btn-block">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-icon waves-effect waves-light btn-danger btn-block" form="resource-delete">
                                        <i class="fa fa-remove"></i>
                                    </button>
                                    <form id="resource-delete" action="{{ route('admin.users.destroy', $User->id)}}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="999">No orders yet!</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="cart-block">
                <div class="card-box">
                    <h4 class="m-t-0 cart-tit"><b>Cart List</b></h4>
                    <hr>
                    <div class="row">
                        @forelse($User->cart as $Item)
                        <div class="col-lg-6 col-xs-12">
                            <div class="card">
                                <img class="card-img-top img-fluid" src="/avatar.png" alt="Card image cap">
                                <div class="card-block">
                                    <h4 class="card-title">{{ $Item->product->parent->name }}</h4>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item b-l-0 b-r-0">Weight : {{ $Item->product->name }}</li>
                                    <li class="list-group-item b-l-0 b-r-0">Price : {{ $Item->product->prices ? $Item->product->prices[0]->price : 0 }}</li>
                                </ul>
                                <a href="#" class="btn btn-icon waves-effect btn-danger btn-block waves-light">Delete</a>
                            </div>
                        </div>
                        @empty
                        <div class="col-xs-12 text-center">
                            <h4>No items in cart!</h4>
                        </div>
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<style type="text/css">
.inven-box{
    -webkit-box-shadow: 0 1px 3px 0 rgba(0,0,0,.2);
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.2);
    -webkit-transition: all .2s ease-in-out;
    transition: all .2s ease-in-out;
    margin-bottom: 30px;
}

.inven-box:hover,
.inven-box:focus{
    -webkit-box-shadow: 0 4px 20px 0 rgba(168,182,191,.6);
    box-shadow: 0 4px 20px 0 rgba(168,182,191,.6);
    transform: translateY(-5px);
}
</style>
@endsection